pick: random

configs:
  win2020:
    os: windows
    isabelle: 2020
# Isabelle 2019 does not run on Circle CI with the current config. It works when installing sbt via "choco install sbt", and then running "refreshenv & sbt test" in cmd (not bash)
#  win2019:
#    os: windows
#    isabelle: 2019
  linux2019:
    os: linux
    isabelle: 2019
  linux2020:
    os: linux
    isabelle: 2020
  macos2020:
    os: macos
    isabelle: 2020
  macos2019:
    os: macos
    isabelle: 2019


defaults:
  machine_config: |
    if os=="windows": return "executor: { name: windows/default }"
    if os=="linux": return "machine: {image: ubuntu-2004:202010-01}"
    if os=="macos": return "macos: {xcode: 11.6.0}"
  isabellehome: |
    if os=="macos": return f"~/install/Isabelle{isabelle}.app/Isabelle"
    return f"~/install/Isabelle{isabelle}"
