version: 2.1

orbs:
  windows: circleci/windows@2.4.0

workflows:
  version: 2
  @{name}:
    when:
      equal: [ @{baserevision}, << pipeline.git.base_revision >> ]
    jobs:
      - test:
          filters:
            branches:
              only:
                - circleci-project-setup
                - master
                - release-candidate
                - test-windows
  no_workflow:
    when:
      not:
        equal: [ @{baserevision}, << pipeline.git.base_revision >> ]
    jobs:
      - do_nothing_job


jobs:
  do_nothing_job:
    docker: [ image: cimg/base:2020.01 ]
    steps:
      - checkout

  test:

    @{machine_config}

#    environment:
#      # Customize the JVM maximum heap limit
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb

    steps:
      - checkout

      # Download and cache Isabelle
      - restore_cache:
          keys:
            - v2-isabelle-@{isabelle}-@{os}
      - run:
          name: Downloading Isabelle @{isabelle} (if needed)
          shell: bash
          command: |
            if ! [ -e "$HOME/install/Isabelle@{isabelle}" ]; then
              mkdir -p ~/install
              case @{os} in
                windows)
                  curl "https://isabelle.in.tum.de/website-Isabelle@{isabelle}/dist/Isabelle@{isabelle}.exe" -o /tmp/isabelle.exe
                  7z x -y -o"$HOME/install" /tmp/isabelle.exe;;
                linux)
                  curl https://isabelle.in.tum.de/website-Isabelle@{isabelle}/dist/Isabelle@{isabelle}_linux.tar.gz | tar -x -z -C ~/install;;
              esac
            fi
      - save_cache:
          paths:
            - ~/install/Isabelle@{isabelle}
          key: v2-isabelle-@{isabelle}-@{os}

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-@{os}-{{ checksum "build.sbt" }}-{{ checksum "publish.sbt" }}
            - v3-dependencies-@{os}-
      - run:
          name: Downloading build dependencies (if needed)
          shell: bash
          command: |
            if ! sha1sum -c ~/dependencies-sha1sum; then
              mkdir -p ~/install
              curl -Ls https://git.io/sbt > ~/install/sbt
              chmod +x ~/install/sbt
              ~/install/sbt update test/update </dev/null
            fi
            sha1sum build.sbt publish.sbt > ~/dependencies-sha1sum
      - save_cache:
          paths:
            - ~/install/sbt
            - ~/.m2
            - ~/.sbt
            - ~/.ivy2
            - $LOCALAPPDATA\Coursier\Cache
            - ~/.cache/coursier
            - ~/dependencies-sha1sum
          key: v3-dependencies-@{os}-{{ checksum "build.sbt" }}-{{ checksum "publish.sbt" }}

      - run:
          name: Running tests
          shell: bash
          command: |
            case @{os} in
              windows)
                # Isabelle process calls rebaseall and then fails, unless we deactivate it
                > ~/install/Isabelle@{isabelle}/contrib/cygwin/isabelle/rebaseall
                cygpath -w ~/install/Isabelle@{isabelle} > .isabelle-home;;
              linux)
                echo ~/install/Isabelle@{isabelle} > .isabelle-home;;
            esac

            # Things to try:
            # - configuring how sbt runs tests (no forking, spawning)
            # - login bash with cleared env (need HOME though)
            # - nohup
            # no </dev/null

            env -i HOME=~ bash --login ~/bin/sbt "testOnly -- -u scalatest-reports"

#            ~/install/sbt "testOnly -- -u scalatest-reports" </dev/null

      - store_test_results:
          path: scalatest-reports